<?php

$title = 'Elimina fornitore';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sei sicuro di voler eliminare il fornitore '<?php echo $this->escapeHtml($supplier->firstname); ?> <?php echo $this->escapeHtml($supplier->lastname); ?>'?
</p>
<?php
$url = $this->url('supplier', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $supplier->id; ?>" />
    <input type="submit" name="del" value = "Si" class = "btn" />
    <input type="submit" name="del" value = "No" class = "btn" />
</div>
</form>