<?php

use Zend\Session\Container;

$user_session = new Container('user');

$title = 'Fornitori';
$this->headTitle($title);
?>



<?php if ($user_session->type == 'administrator') { ?>
  <div class="row">
    <div class="col-xs-6"><h1><?php echo $this->escapeHtml($title); ?></h1></div>
    <div class="col-xs-6 align-right">
      <a href="<?php echo $this->url('supplier', array('action'=>'add'));?>" class = "btn">inserisci fornitore</a>
    </div>
  </div>
        
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Ragione sociale</th>
            <th>Nome</th>
            <th>Cognome</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($suppliers as $supplier) : ?>
            <tr>
        	    <td><?php echo $this->escapeHtml($supplier->id);?></td>
        	    <td><?php echo $this->escapeHtml($supplier->companyname);?></td>
        	    <td><?php echo $this->escapeHtml($supplier->firstname);?></td>
        	    <td><?php echo $this->escapeHtml($supplier->lastname);?></td>
                <td>
                    <a href="<?php echo $this->url('supplier',
                        array('action'=>'edit', 'id' => $supplier->id));?>" class = "btn">modifica</a>
                    <a href="<?php echo $this->url('supplier',
                        array('action'=>'delete', 'id' => $supplier->id));?>" class = "btn">elimina</a>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>

<?php } else {  ?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <form class="form-horizontal" role="form">

      <div class="bs-accordion">
          <div class="panel-group" id="accordion">
              <?php 
              $x = 1;
              foreach ($suppliers as $supplier) : ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $x;?>">

                            <?php echo $this->escapeHtml($supplier->specialization);?>
                        </a>
                        </h4>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </div>
                    <div id="collapse<?php echo $x;?>" class="<?php echo ($x == 1 ? 'panel-collapse collapse in' : 'panel-collapse collapse'); ?>">
                        <div class="panel-body">
                          <?php if(!empty($supplier->companyname)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Ragione sociale</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->companyname; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->lastname)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Referente</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->firstname . ' ' . $supplier->lastname; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->taxnumber)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Partita IVA</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->taxnumber; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->email)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Email</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->email; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->pec)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">PEC</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->pec; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->telephone)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Telefono</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->telephone; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->fax)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Fax</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->fax; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->mobile)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Mobile</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->mobile; ?>
                              </div>
                            </div>
                          <?php } ?>

                          <?php if(!empty($supplier->address)) { ?>
                            <div class="form-group">
                              <label class="col-sm-2 control-label color-label">Indirizzo</label>
                              <div class="col-sm-10">
                                <?php echo $supplier->address; ?>
                              </div>
                            </div>
                          <?php } ?>

                        </div>
                    </div>
                </div>


              <?php $x = $x + 1;
            endforeach; ?>

          </div>
        </div>
    </form>

<?php } ?>
