<?php
use Zend\Session\Container;

$user_session = new Container('user');

$title = $condominium->name;
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="form-horizontal">

    <div class="form-group">
        <label for="edit" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <a href="<?php echo $this->url('bacheca', array('action'=>'add'));?>" class = "btn">scrivi in bacheca</a>
        </div>
    </div>

    <?php foreach ($messages as $message) : ?>

        <div class="form-group">
            <label for="creationdate" class="col-sm-2 control-label color-label">Data</label>
            <div class="col-sm-10">
                <?php echo $this->escapeHtml($message->creationdate);?>
            </div>
        </div>
        <div class="form-group">
            <label for="author" class="col-sm-2 control-label color-label">Autore</label>
            <div class="col-sm-10">
                <?php echo $this->escapeHtml($message->author);?>
            </div>
        </div>
        <div class="form-group">
            <label for="message" class="col-sm-2 control-label color-label">Messaggio</label>
            <div class="col-sm-10">
                <?php echo $message->message;?>
            </div>
        </div>
        <div class="form-group">
            <label for="edit" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <a href="<?php echo $this->url('bacheca', array('action'=>'edit', 'id' => $message->id));?>"class = "btn">modifica</a>
                <a href="<?php echo $this->url('bacheca', array('action'=>'delete', 'id' => $message->id));?>"class = "btn">elimina</a>
                <a href="<?php echo $this->url('bacheca', array('action'=>'send', 'id' => $message->id));?>"class = "btn">invia email al condominio</a>                    
            </div>
        </div>

    <?php endforeach; ?>

</div>


