<?php

$title = 'Login condomino';
$this->headTitle($title);
?>

<div id = "login">
	<p>
	<h1><?php echo $this->escapeHtml($title); ?></h1>
	</p>

	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('condomino', array('action' => 'login')));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	?>
	<div class="form-group">
		<?php echo $this->formRow($form->get('username')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('password')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('remember')); ?>
		<span class = "delimeter">&nbsp;|&nbsp;</span>
		<a href = "/condomino/recovery">Recupera password</a>
	</div>
	<div class="row">
	  <div class="col-xs-6"></div>
	  <div class="col-xs-6 align-right"><?php echo $this->formSubmit($form->get('submit')); ?></div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>


