<?php

$title = 'Registrazione condomino';
$this->headTitle($title);
?>
<div id = "register">
	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('condomino', array('action' => 'register')));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	?>

	<div class="form-group">
		<?php echo $this->formRow($form->get('firstname')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('lastname')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('email')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('fiscalcode')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('password')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formRow($form->get('password_verify')); ?>
	</div>
	<div class="form-group">
		<strong class = "color-label mandatory">Tutela della privacy</strong><br />
		Pienamente informato/a dell'<a href = "/informativa-privacy.txt" title = "Informativa privacy" target = "_privacy">Informativa sulla privacy</a> ai sensi dell'art. 13 del Decreto Legislativo 30 giugno 2003 n. 196 ed ai sensi degli articoli 23 e 26 dello stesso:
		<p>
			<?php echo $this->formRow($form->get('privacy')); ?>
			esprimo il consenso al trattamento dei miei dati personali al fine di consentire che venga fornito il servizio o eseguita la prestazione richiesta.
		</p>
	</div>
	<!--
	<div class="form-group">
		<?php //echo $this->formRow($form->get('condominium')); ?>
	</div>
	-->
	<div class="form-group">
		<a class = "btn" href = "javascript:history.back();">annulla</a>
		<?php echo $this->formSubmit($form->get('submit')); ?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>

