<?php

$title = 'Dati del condomino';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<form class="form-horizontal" role="form">

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Nome</label>
      <div class="col-sm-10">
        <?php echo $condomino->firstname; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Cognome</label>
      <div class="col-sm-10">
        <?php echo $condomino->lastname; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Email</label>
      <div class="col-sm-10">
        <?php echo $condomino->email; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">PEC</label>
      <div class="col-sm-10">
        <?php echo $condomino->pec; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Username</label>
      <div class="col-sm-10">
        <?php echo $condomino->username; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Fiscalcode</label>
      <div class="col-sm-10">
        <?php echo $condomino->fiscalcode; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Consigliere</label>
      <div class="col-sm-10">
        <?php echo $condomino->adviser == 'Y' ? 'Si' : 'No'; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Prima unità immobiliare</label>
      <div class="col-sm-10">
        <?php echo $condomino->unit_1; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Seconda unità immobiliare</label>
      <div class="col-sm-10">
        <?php echo $condomino->unit_2; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Terza unità immobiliare</label>
      <div class="col-sm-10">
        <?php echo $condomino->unit_3; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Ricevi email avvisi e scadenze</label>
      <div class="col-sm-10">
        <?php echo $condomino->notice == 'Y' ? 'Si' : 'No'; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Ricevi email di segnalazioni e guasti</label>
      <div class="col-sm-10">
        <?php echo $condomino->request == 'Y' ? 'Si' : 'No'; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label">Ricevi email messaggi in bacheca</label>
      <div class="col-sm-10">
        <?php echo $condomino->bacheca == 'Y' ? 'Si' : 'No'; ?>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label color-label"></label>
      <div class="col-sm-10">
        <a href="<?php echo $this->url('condomino', array('action'=>'update'));?>"class = "btn">modifica</a>
      </div>
    </div>
  
</form>