<?php

$title = 'Elimina categoria';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sei sicuro di voler cancellare la categoria '<?php echo $this->escapeHtml($category->name); ?>'?
</p>
<?php
$url = $this->url('category', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $category->id; ?>" />
    <input type="submit" name="del" value="Si" class = "btn" />
    <input type="submit" name="del" value="No" class = "btn" />
</div>
</form>