<?php

$title = 'Elimina condominio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sei sicuro di voler cancellare il condominio '<?php echo $this->escapeHtml($condominium->name); ?>'?</p>
<?php
$url = $this->url('condominium', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $condominium->id; ?>" />
    <input type="submit" name="del" value="Si" class = "btn" />
    <input type="submit" name="del" value="No" class = "btn" />
</div>
</form>