<?php

$title = 'Nuova segnalazione';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('request', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
	<?php echo $this->formRow($form->get('type_id')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('object')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('message')); ?>
</div>
<div class="form-group">
	<input type = "hidden" id = "status_id" name = "status_id" value = "O" />
</div>
<div class="form-group">
	<a class = "btn" href = "javascript:history.back();">annulla</a>
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>


