<?php

$title = 'Elimina messaggio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sei sicuro di voler eliminare questo messaggio dalla bacheca?</p>

<?php
$url = $this->url('bacheca', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
	    <input type="hidden" name="id" value="<?php echo (int) $bacheca->id; ?>" />
	    <input type="submit" name="del" value = "Si" class = "btn" />
	    <input type="submit" name="del" value = "No" class = "btn" />
	</div>
</form>