<?php

$title = 'Modifica messaggio';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('bacheca',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('condominium_id'));
echo $this->formHidden($form->get('condomino_id'));
?>

<div class="form-group">
	<?php echo $this->formRow($form->get('object')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('message')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('creationdate')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('modifydate')); ?>
</div>
<div class="form-group">
	<a class = "btn" href = "javascript:history.back();">annulla</a>
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<br />
<?php echo $this->form()->closeTag(); ?>


