<?php

$title = 'Modifica documento';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'document',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('category_id'));
echo $this->formHidden($form->get('condominium_id'));
?>
<?php
$url_preview = $this->url('document', array('action' => 'view', 'id' => $this->id)); ?>
<a href = "<?php echo $url_preview; ?>" target = "_blank" class = "btn">anteprima</a>

<div class="form-group">
	<?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('description')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('filename')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('mime')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('size')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('creationdate')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('modifydate')); ?>
</div>
<div class="form-group">
	<a class = "btn" href = "javascript:history.back();">annulla</a>
	<?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>


