<?php
/*
$title = 'Preview documento';
$this->headTitle($title);



echo $document->filename . '<br />';
echo $document->mime . '<br />';
echo $document->size . '<br />';
echo var_dump($document->data) . '<br />';


  

header("Content-length: $document->size");
header("Content-type: $document->mime");
header("Content-Disposition: attachment; filename=$document->filename");
header("Content-transfer-encoding: binary");        
        ob_end_clean();
flush();

echo $document->data;
*/  
?>

