<?php

$title = $condominium->name;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	Benvenuto amministratore!<br />
    Di seguito le funzionalità per gestire il condominio selezionato.
</p>
<p>
	Clicca qui per abilitare condomini in attesa di validazione
	<a href="<?php echo $this->url('condomino', array('action'=>'validate'));?>" class = "btn">da validare</a>
</p>
