<?php 
use Zend\Session\Container;

$user_session = new Container('user');

$title = 'Amministratore';
$this->headTitle($title);
?>

<div class="row">
  <div class="col-xs-6"><h1><?php echo $this->escapeHtml($title); ?></h1></div>
  <div class="col-xs-6 align-right">
    <a class = "btn" href = "javascript:history.back();">indietro</a>
  </div>
</div>

<?php if ($user_session->type == 'administrator') { ?>
	<p>
	    <a href="<?php echo $this->url('administrator', array('action'=>'add'));?>" class = "btn">inserisci amministratore</a>
	</p>

	<table class="table">
		<tr>
		    <th>ID</th>
		    <th>Ragione sociale</th>
		    <th>Nome</th>
		    <th>Cognome</th>
		    <th>&nbsp;</th>
		</tr>
		<?php foreach ($administrators as $administrator) : ?>
			<tr>
			    <td><?php echo $this->escapeHtml($administrator->id);?></td>
			    <td><?php echo $this->escapeHtml($administrator->companyname);?></td>
			    <td><?php echo $this->escapeHtml($administrator->firstname);?></td>
			    <td><?php echo $this->escapeHtml($administrator->lastname);?></td>
			    <td>
			        <a href="<?php echo $this->url('administrator',
			            array('action'=>'edit', 'id' => $administrator->id));?>" class = "btn">modifica</a>
			        <a href="<?php echo $this->url('administrator',
			            array('action'=>'delete', 'id' => $administrator->id));?>" class = "btn">elimina</a>
			    </td>
			</tr>
		<?php endforeach; ?>
	</table>

<?php } else {  ?>

	
	<form class="form-horizontal" role="form">

		<div class="bs-accordion">
          	<div class="panel-group" id="accordion">
              <?php 
              $x = 1; 
              foreach ($administrators as $administrator) : ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $x;?>">
                            <?php echo $this->escapeHtml($administrator->companyname);?>
                        </a>
                        </h4>
                        <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                    </div>
					<div id="collapse<?php echo $x;?>" class="<?php echo ($x == 1 ? 'panel-collapse collapse in' : 'panel-collapse collapse'); ?>">
						
                    	<div class="panel-body">
			    
						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Referente</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->firstname . ' ' . $administrator->lastname; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Email</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->email; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">PEC</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->pec; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Telefono</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->telephone; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Cellulare</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->mobile; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Fax</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->fax; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Sito web</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->website; ?>
						      </div>
						    </div>

						    <div class="form-group">
						      <label class="col-sm-2 control-label color-label">Orario d'ufficio</label>
						      <div class="col-sm-10">
						        <?php echo $administrator->officehours; ?>
						      </div>
						    </div>
				        </div>
				    </div>
				</div>

				<?php $x = $x + 1;
            	endforeach; ?>
			</div>
		</div>
	</form>
	
<?php } ?>