<?php

$title = 'Modifica password';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'administrator',
    array(
        'action' => 'password',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
	<?php echo $this->formRow($form->get('old_password')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('new_password')); ?>
</div>
<div class="form-group">
	<?php echo $this->formRow($form->get('password_verify')); ?>
</div>
<div class="form-group">
	<a class = "btn" href = "javascript:history.back();">annulla</a>
	<?php echo $this->formSubmit($form->get('change')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>


